name: "Collect IPs"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'
    
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php main.php
          git config --global user.email "ermanaostida@gmail.com"
          git config --global user.name "gugun0977"
          git add -A
          git commit -m "Automatic update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
